### ISSUE TITLE
Could you provide some wikis

### ISSUE THREAD

**Issue by ysmintor** [Piasy/AndroidTDDBootStrap#13]
I am a beginner on this project, and it is true that some of third library I am not know before. The most important problem for me is that when I download this repo, open it with Android Studio (which vision is 2.3) , however it just building gradle project info. How could I continue ? 
I just want to study this, but it seems that there is a steep hill for beginner.

**Comment by Piasy** [comment]
## Build tips
+  Sign key config
    -  Place KeyStore file in some place, and create a TemplateKeyStore.properties, and config the KeyStore in it, include `keystore`, `keystore.password`, `key.password`, `key.alias`.
+  To clone all submodules, please use `git clone --recursive git@github.com:Piasy/AndroidTDDBootStrap.git`
+  use flavor to control server configuration, use build type to control log behavior
    -  `dev` for development server, `prod` for production server
    -  `debug` enable log and dev tools, disable crash and analytics, `release` against it
