### ISSUE TITLE
duplicate compileOptions in app's build.gradle

### ISSUE THREAD

**Issue by Luolc** [Piasy/AndroidTDDBootStrap#14]
[AndroidTDDBootStrap/app/build.gradle](https://github.com/Piasy/AndroidTDDBootStrap/blob/master/app/build.gradle)

At line 57-60 and 77-80, `compileOptions` is defined twice.

**Comment by Piasy** [comment]
Yes, and both of them are not necessary, it has been added in [okbuck.gradle](https://github.com/Piasy/AndroidTDDBootStrap/blob/master/buildsystem/okbuck.gradle).

**Comment by Luolc** [comment]
Wow, get it. 
I've cloned this project and learnt for some days but still with many questions :( 
Much knowledge involved. A lot to learn..

**Comment by Piasy** [comment]
lol, don't worry, both of us have a lot to learn. Besides, this project is not perfect, welcome to file an issue or pr!
