### ISSUE TITLE
 clone 操作失败

### ISSUE THREAD

**Issue by LouisMari1991** [Piasy/AndroidTDDBootStrap#21]
$ git clone --recursive https://github.com/Piasy/AndroidTDDBootStrap.git
Cloning into 'AndroidTDDBootStrap'...
remote: Counting objects: 6201, done.
error: RPC failed; curl 56 SSL read: error:00000000:lib(0):func(0):reason(0), errno 10054
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by Piasy** [comment]
That's should not be my fault :)
