### ISSUE TITLE
有点疑惑

### ISSUE THREAD

**Issue by htoooth** [Piasy/AndroidTDDBootStrap#3]
数据都来自网上，使用Gson来做解析变成了POJO，POJO继承serializable，能在bundle 中传递，那Auto-parcel在什么情况下使用？

**Comment by Piasy** [comment]
首先，如果只是为了从Json反序列化，POJO无需 **实现** Serializable，而且，非必须情况下， **不建议** 实现Serializable，[参考](https://github.com/Piasy/notes/blob/master/Android-Java%2FEffectiveJava.md#serialization)；
其次，在bundle中传递应该是实现 Parcelable，而不是Serializable；
再次，auto-parcel是为了实现immutable，并可选实现builder模式，和Gson没关系，而且，为了让auto-parcel和Gson能同时使用，还需要自定义AutoGenTypeAdapterFactory，[参考实现](https://gist.github.com/Piasy/fa507251da452d36b221)。

**Comment by htoooth** [comment]
@Piasy 谢谢！
