### ISSUE TITLE
更新了？

### ISSUE THREAD

**Issue by gxmdboy** [Piasy/AndroidTDDBootStrap#4]

**Comment by Piasy** [comment]
?

**Comment by gxmdboy** [comment]
第一次issue操作失误...
刚整个项目下载看看，不知道为什么解压后AndroidCodeQualityConfig，base,testbase这三个文件夹是空的
还有无法下载com.github.okbuilds:okbuild-gradle-plugin:2.0.0-alpha1这个插件
环境：win10 AS2.1.1

**Comment by Piasy** [comment]
找不到 plugin 的问题刚才我提了个 commit 已经解决。至于空文件夹的问题，请按照 README 进行 clone
