### ISSUE TITLE
麻烦问下这个工程是在window上编译吗

### ISSUE THREAD

**Issue by 609685846** [Piasy/AndroidTDDBootStrap#5]
看到很多sh，win下编译好多问题

**Comment by Piasy** [comment]
mac 系统。不保证 windows 能正常编译。抱歉 :(

**Comment by hunji66** [comment]
windows 能正常编译及运行，我已经试过了。

**Comment by Piasy** [comment]
那就应该是 clone 方式的问题，请按照 README 中的方式进行 clone
