### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by HelloVass** [Piasy/AndroidTDDBootStrap#7]
Error:(170, 1) A problem occurred evaluating project ':app'.
> Could not find property 'BUG_TAGS_API_SECRET' on com.bugtags.library.gradle.BugtagsExtension_Decorated@76e10c3f.

:)

**Comment by Piasy** [comment]
just create a file named `gradle.properties` and add `BUG_TAGS_API_SECRET = ""` into it

**Comment by Piasy** [comment]
Bugtags has been removed.
